POST http://localhost:3003/usuario/cadastrar
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "teste1234"
}

###
GET http://localhost:3003/usuario/login
Content-Type: application/json

{
    "email": "rafael@gmail.com",
    "password": "senha1234"
}

###
GET http://localhost:3003/usuario/profile
authorization: "token"
